name: Build and deploy ASP.NET app to Azure Web App - DarakhHC-API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore DarakhsHC-API.sln

      - name: Build & Package project
        working-directory: DarakhsHC-API
        run: >
          msbuild DarakhsHC-API.csproj
          /p:Configuration=Release
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package

      - name: Prepare publish folder
        run: |
          if (!(Test-Path DarakhsHC-API\publish)) {
            mkdir DarakhsHC-API\publish
          }
          xcopy DarakhsHC-API\obj\Release\Package\PackageTmp\* DarakhsHC-API\publish\ /E /I /Y

      - name: Verify publish folder
        run: dir DarakhsHC-API\publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: DarakhsHC-API\publish
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: DarakhHC-API
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C3C95786A418449E87E00FDEBEC9FE8A }}









